version: '3.3'

services:
  mysqldb: 
    container_name: ${DB_HOST}
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    hostname: ${DB_HOST}
    volumes:
      - ../../volumes/db:/var/lib/mysql  
    #env_file:
    #  - ./JirehServer/.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
    expose:
      - 3306  
   # ports:
    #  - $DB_LOCAL_PORT:$DB_DOCKER_PORT

#app:
 # build: .
  #depends_on:
  #  - mysqldb
  #links:
  #  - mysqldb        
  #ports:
  #  - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT