version: '3.3'

services:
  mysqldb: 
    container_name: dbJireh
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    hostname: ${DB_HOST}
    volumes:
      - ../../volumes/db:/var/lib/mysql  
    #env_file:
    #  - ./JirehServer/.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
    expose:
      - 3306  
    ports:
      - $DB_LOCAL_PORT:${DB_DOCKER_PORT}
    restart: always      
  jireh-server:
    container_name: jireh-server
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
      - DB_HOST=${DB_HOST}
      - DB_LOCAL_PORT=${DB_LOCAL_PORT}
    build:
      context: ./JirehServer
      dockerfile: Dockerfile
    image: jireh-server:0.0.1
    ports:
      - 3000:3000
    restart: always
#app:
 # build: .
  #depends_on:
  #  - mysqldb
  #links:
  #  - mysqldb        
  #ports:
  #  - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT